export const SEARCH_CHANGED = "SEARCH_CHANGED";

export const GET_ROBOS_PENDING = "GET_ROBOS_PENDING";
export const GET_ROBOS_SUCCESS = "GET_ROBOS_SUCCESS";
export const GET_ROBOS_REJECT = "GET_ROBOS_REJECT";
